# Generated by Django 4.2.4 on 2023-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gest_pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="direccion",
            field=models.CharField(max_length=50, verbose_name="La dirección"),
        ),
    ]
